[package]
name = "helloskill-editor-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.7.0"
actix-web = "4"
env_logger = "0.10"
log = "0.4"
serde = { version = "1.0.217", features = ["derive"] }
